version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teST_09
      POSTGRES_DB: postgres

    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data

  app:
    build: ./app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db